### PR TITLE
4.4 keys update

### LINKED ISSUE #137: some values for V4.4 pre-downlad package are missing
Hello developer.

When I try to demux the new video usm files in the pre-download package for V4.4, it shows me no values (key, version) found in the versions.json. could you please teach me how to find the required values so that I could demux it?

In appreciation

### LINKED ISSUE #138: Update For 4.4 Keys

### PR DESCRIPTION
**Pull request by Asayu233**
resolve #137 
resolve #138

### CODE REVIEW

**Comment by Asayu233** [comment]
sorry about the format, cuz I changed an editor...

**Comment by HRB-YuPai** [comment]
Hi, Asayu. All the keys for 4.4 are still incorrect. Could you please tell me how to get those keys so that I could try to grab them?

**Comment by iPeer** [comment]
> Hi, Asayu. All the keys for 4.4 are still incorrect. Could you please tell me how to get those keys so that I could try to grab them?

The keys are valid and can extract the 4.4 cutscenes just fine. Make sure you're copying the correct [raw](https://raw.githubusercontent.com/ToaHartor/GI-cutscenes/c7d9ccf7dd2c48c2a3674784865afe82b119eb3c/versions.json) data into your `versions.json` file.

**Comment by Yish1** [comment]
Happy new year my bro ！
Could you please share me how to get this keys?
Thanks!

**Comment by Asayu233** [comment]
> Could you please tell me how to get those keys so that I could try to grab them?

> Happy new year my bro ！ Could you please share me how to get this keys? Thanks!

Happy new year! I just used the debugger to analyze the code, and dump the keys from memory.
So I can't provide any help in capturing packets, sorry...

**Comment by HRB-YuPai** [comment]
@Asayu233  Sorry to bother you again. I just tried the key in [this json,](https://raw.githubusercontent.com/ToaHartor/GI-cutscenes/c7d9ccf7dd2c48c2a3674784865afe82b119eb3c/versions.json) and it still does not decrypt the 4 new CGs. Could you please help me about this?

**Comment by Yish1** [comment]
> > Could you please tell me how to get those keys so that I could try to grab them?
> 
> > Happy new year my bro ！ Could you please share me how to get this keys? Thanks!
> 
> Happy new year! I just used the debugger to analyze the code, and dump the keys from memory. So I can't provide any help in capturing packets, sorry...

okey,i see

**Comment by Yish1** [comment]
> @Asayu233 Sorry to bother you again. I just tried the key in [this json,](https://raw.githubusercontent.com/ToaHartor/GI-cutscenes/c7d9ccf7dd2c48c2a3674784865afe82b119eb3c/versions.json) and it still does not decrypt the 4 new CGs. Could you please help me about this?

I have just tried to decrypt the Haideng Festival cg, and it worked well

**Comment by HRB-YuPai** [comment]
@Yish1 Could you please tell me which file (file name) you tried to decrypt from 4.4? I tried all usm files from the update pack of 4.3 to 4.4 (Chinese version of Genshin Impact), and all of them gives me the wrong decrypted file.

**Comment by Jerry12228** [comment]
may 

> Hi, Asayu. All the keys for 4.4 are still incorrect. Could you please tell me how to get those keys so that I could try to grab them?

could iridrum do this？
but i couldn't get proto files
I'm also trying to do that by my self because I'm really afraid of losing key of usm one day

**Comment by ToaHartor** [comment]
Thank you again for the keys !

**Pull request merged**
