### PR TITLE
4.6 keys update

### LINKED ISSUE #151: 大佬！我们急需4.6的key！！！

### PR DESCRIPTION
**Pull request by Asayu233**
resolve #151

### CODE REVIEW

**Comment by jzfzzzz** [comment]
> resolve #151

we need the key of "Cs_Sumeru_LD130380801_TOS",thank you

**Comment by Caelum008** [comment]
just a question: is this [cutscene](https://youtu.be/-ulocKe61mg) and the one with Clervie not included in the files?

**Comment by BUnipendix** [comment]
> 
> 
> 
> 
> > resolve #151
> 
> we need the key of "Cs_Sumeru_LD130380801_TOS",thank you
> 

#8
别急，要等传说任务开启才能获得

**Comment by BUnipendix** [comment]
> just a question: is this [cutscene](https://youtu.be/-ulocKe61mg) and the one with Clervie not included in the files?

#75

**Comment by Caelum008** [comment]
> > just a question: is this [cutscene](https://youtu.be/-ulocKe61mg) and the one with Clervie not included in the files?
> 
> #75

noted. thank you for answering!

**Comment by jzfzzzz** [comment]
> > > resolve #151
> > 
> > 
> > we need the key of "Cs_Sumeru_LD130380801_TOS",thank you
> 
> #8 别急，要等传说任务开启才能获得

仆人的传说任务不是已经上线了吗

**Comment by BUnipendix** [comment]
> > > > resolve #151
> > > 
> > > 
> > > we need the key of "Cs_Sumeru_LD130380801_TOS",thank you
> > 
> > #8 别急，要等传说任务开启才能获得
> 
> 仆人的传说任务不是已经上线了吗

这是赛诺的，只有旅行者对峙仆人的那段是预渲染的，其它全是实时渲染

**Comment by BUnipendix** [comment]
> > > > > resolve #151
> > > > 
> > > > 
> > > > we need the key of "Cs_Sumeru_LD130380801_TOS",thank you
> > > 
> > > #8 别急，要等传说任务开启才能获得
> > 
> > 仆人的传说任务不是已经上线了吗
> 
> 这是赛诺的，除此之外只有旅行者对峙仆人的那段是预渲染的，其它全是实时渲染

**Comment by ToaHartor** [comment]
Thank you !

**Comment by Toa-Pohatu** [comment]
Where do I get Natlan keys??

**Comment by Questwalker** [comment]
> Where do I get Natlan keys??

In [https://github.com/ToaHartor/GI-cutscenes/blob/main/versions.json](https://github.com/ToaHartor/GI-cutscenes/blob/main/versions.json). You won't find anything Natlan related in a 6-month-old pull request. Note that the 5.1 keys have been not grabbed yet, only the 5.0 keys.

**Pull request merged**
