### PR TITLE
Add new usm name

### PR DESCRIPTION
**Pull request by BiosNod**
Add Cs_YLLQ1012008_EulaShow

### CODE REVIEW

**Comment by Unknow-404** [comment]
It's an unfinished cutscene, I do not suggest to add it.

**Comment by BiosNod** [comment]
> It's an unfinished cutscene, I do not suggest to add it.

I guess people still want to watch everything .usm. For example, I wanted :D And it was an interesting sketch.

**Comment by BUnipendix** [comment]
> I wondered where's the real Eula show, it can't be realtime render. 

It deleted after version 1.5

**Comment by ToaHartor** [comment]
I don't mind adding it to the version file, as it is a file that exist ; just no longer available for obvious reasons. I can add a disclaimer in the README saying that if the cutscene looks unfinished, it's normal 😄.

> I wondered where's the real Eula show, it can't be realtime render.
Pretty sure the cutscene appears in Eula's story quest, and since it doesn't really appear in the files, it should be realtime rendered afaik.

**Pull request merged**
