### PR TITLE
3.7 keys update

### LINKED ISSUE #103: 3.7 Key Update

### PR DESCRIPTION
**Pull request by Asayu233**
close #103

### CODE REVIEW

**Comment by SuperYoko** [comment]
Keep format (And thank you for the 3.7 key!

**Comment by CarterLi** [comment]
Key of Cs_Sumeru_EQ401101101_KP is 0

**Comment by JRSKelvin** [comment]
Thank you @Asayu233 for the 3.7 key, and @CarterLi for Cs_Sumeru_EQ401101101_KP seems in the future release cutscene, so currently replace with 0.

**Review by BUnipendix — APPROVED** [review]
thank you

**Comment by ToaHartor** [comment]
Thank you for the work !

**Pull request merged**
