### PR TITLE
4.1 keys update

### LINKED ISSUE #117: Update for the 4.1 keys?
Thanks...

### LINKED ISSUE #118: 4.1 Keys?

### PR DESCRIPTION
**Pull request by Asayu233**
resolve #117 
resolve #118

### CODE REVIEW

**Comment by shimiandezhu66** [comment]
How about the version for 14006 and 40126?

**Comment by gszshdzz** [comment]
> How about the version for 14006 and 40126?

#8 

> However starting version 2.7, the second keys might now be sent when the game needs it, therefore either in a packet at the beginning of a cutscene during a quest or during the login. 

The key can only be dumped after the video has been played in the game

**Comment by shimiandezhu66** [comment]
> > How about the version for 14006 and 40126?
> 
> #8
> 
> > However starting version 2.7, the second keys might now be sent when the game needs it, therefore either in a packet at the beginning of a cutscene during a quest or during the login.
> 
> The key can only be dumped after the video has been played in the game

I see.Thank you so much...

**Comment by shimiandezhu66** [comment]
> > How about the version for 14006 and 40126?
> 
> #8
> 
> > However starting version 2.7, the second keys might now be sent when the game needs it, therefore either in a packet at the beginning of a cutscene during a quest or during the login.
> 
> The key can only be dumped after the video has been played in the game

But I really want to learn how can i get the key.
Could you provide a packet capture tutorial for me?

**Comment by gszshdzz** [comment]
> > > How about the version for 14006 and 40126?
> > 
> > 
> > #8
> > > However starting version 2.7, the second keys might now be sent when the game needs it, therefore either in a packet at the beginning of a cutscene during a quest or during the login.
> > 
> > 
> > The key can only be dumped after the video has been played in the game
> 
> But I really want to learn how can i get the key. Could you provide a packet capture tutorial for me?

Sorry, but I want to know it too
It may require tools like Akebi

**Comment by shimiandezhu66** [comment]
> > > > How about the version for 14006 and 40126?
> > > 
> > > 
> > > #8
> > > > However starting version 2.7, the second keys might now be sent when the game needs it, therefore either in a packet at the beginning of a cutscene during a quest or during the login.
> > > 
> > > 
> > > The key can only be dumped after the video has been played in the game
> > 
> > 
> > But I really want to learn how can i get the key. Could you provide a packet capture tutorial for me?
> 
> Sorry, but I want to know it too It may require tools like Akebi

Thanks...

**Comment by Jirehlov** [comment]
催更~

**Comment by ikenxuan** [comment]
求4.2key

**Comment by shimiandezhu66** [comment]
@Asayu233 I really like the main plot of 4.2 so much, and I really want to collect the cutscenes of 4.2. I wonder if you have finished it? After finishing it, I hope you can update the main plot key of 4.2. Thank you very much and I wish you a happy game.

**Comment by ToaHartor** [comment]
As always I'm late to the party, thank you as always for the work on the keys ! This might also fix #124

**Comment by Asayu233** [comment]
> @Asayu233 I really like the main plot of 4.2 so much, and I really want to collect the cutscenes of 4.2. I wonder if you have finished it? After finishing it, I hope you can update the main plot key of 4.2. Thank you very much and I wish you a happy game.

4.2 all keys now updated ;)

**Pull request merged**
