### PR TITLE
3.4 keys update

### PR DESCRIPTION
**Pull request by Asnxthaony**

### CODE REVIEW

**Comment by BUnipendix** [comment]
请问你是用的什么抓包工具？

**Comment by cookie797** [comment]
emmm....The key you submitted for "3.4", the "Liyue" part may not be correct. The value "0" of the key may be wrong.

> {
					"key": 0,
					"version": "40093",
					"videos": [
						"Cs_Liyue_EQ4009306_HDJ1",
						"Cs_Liyue_EQ4009311_HDJ2_Boy",
						"Cs_Liyue_EQ4009311_HDJ2_Girl"
					]
				}

**Comment by Unknow-404** [comment]
> emmm....The key you submitted for "3.4", the "Liyue" part may not be correct. The value "0" of the key may be wrong.
> 
> > {
> > "key": 0,
> > "version": "40093",
> > "videos": [
> > "Cs_Liyue_EQ4009306_HDJ1",
> > "Cs_Liyue_EQ4009311_HDJ2_Boy",
> > "Cs_Liyue_EQ4009311_HDJ2_Girl"
> > ]
> > }

The key can only be obtained after the activity starts.

**Review by cookie797 — APPROVED** [review]

**Comment by ToaHartor** [comment]
Thank you for the keys ! I've been busy lately so I didn't have the time to look into it and merge. Time to update then.

**Pull request merged**
