### PR TITLE
support hca decryption and optimize

### PR DESCRIPTION
**Pull request by BUnipendix**
cache decrypted hca data in memory to decrease disk io and increased speed by 15% to 35% (test on my computer).
set "-e ffmpeg" to enable decrypted hca export, because ffmpeg support hca decode.

### CODE REVIEW

**Comment by ToaHartor** [comment]
Thanks for the PR. 
So, if I understand well, it improves the extraction time by keeping the HCA data in memory (which is a good idea considering no one will actually read the raw HCA file). And if FFMPEG is used, then only the decryption is necessary since it natively supports HCA files.

Did I get that correctly ?

**Comment by BUnipendix** [comment]
> Thanks for the PR. 
> So, if I understand well, it improves the extraction time by keeping the HCA data in memory (which is a good idea considering no one will actually read the raw HCA file). And if FFMPEG is used, then only the decryption is necessary since it natively supports HCA files.
> 
> Did I get that correctly ?

yes

**Comment by ToaHartor** [comment]
Alright, so I tested the code a bit (on Windows), and I was wondering if you also got this error during the merge (with `-loglevel trace`) : 

```
[matroska @ 0000024e5aff7c40] No wav codec tag found for codec hca
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:4 --
```

There might be a fix to it, by adding in the codec section `-c:a pcm_s16le`.

**Comment by BUnipendix** [comment]
> Alright, so I tested the code a bit (on Windows), and I was wondering if you also got this error during the merge (with `-loglevel trace`, with the cutscene `Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy.usm`) :
> 
> ```
> [matroska @ 0000024e5aff7c40] No wav codec tag found for codec hca
> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> Error initializing output stream 0:4 --
> ```
> 
> There might be a fix to it, by adding in the codec section `-c:a pcm_s16le`.
> 
> Does FFMPEG need additional configuration to automatically detect it ?

yes. I merge it with my own script.So I didn't test its own merge features.

**Comment by BUnipendix** [comment]
> Alright, so I tested the code a bit (on Windows), and I was wondering if you also got this error during the merge (with `-loglevel trace`, with the cutscene `Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy.usm`) :
> 
> ```
> [matroska @ 0000024e5aff7c40] No wav codec tag found for codec hca
> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> Error initializing output stream 0:4 --
> ```
> 
> There might be a fix to it, by adding in the codec section `-c:a pcm_s16le`.
> 
> Does FFMPEG need additional configuration to automatically detect it ?

I use this FFMPEG encode option to merge mkv.

**Comment by ToaHartor** [comment]
Alright, I have some testing to do to see if I can copy the codec for the video and subtitles and specify the one for the audio. After that, I can merge this.

**Pull request closed without merging**
