### PR TITLE
3.2 keys update

### PR DESCRIPTION
**Pull request by Asnxthaony**

### CODE REVIEW

**Comment by BUnipendix** [comment]
???

**Comment by phuchptty** [comment]
yeah. They even didn't change it
But we should merge after the 3.2 complete release

**Comment by ToaHartor** [comment]
Thank you, can confirm the keys are valid. Will merge wednesday then.

**Comment by BUnipendix** [comment]
> Thank you, can confirm the keys are valid. Will merge wednesday then.

all the videos can play normally.

**Pull request merged**
